<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>NBP</title>
    <meta name="author" content="Mateusz Wojno">
    <meta name="description" content="NBP"/>
    <meta http-equiv="X-Ua-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="assets/style/currencyDenomination.css" type="text/css">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="script.js"></script>
    <script type="text/javascript" src="jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="jquery.validate.min.js"></script>
</head>
<body>

<main>
    <div class=" col-12 col-sm-8 col-md-6 col-lg-4 col-xl-3 mx-auto bg-light" id="currencyDenomination">
        <div class="row">
            <div class="d-flex justify-content-center mb-3 pb-3 pt-3" id="currencyDenominationHeader">
                <h1>Denomination of currency</h1>
            </div>
        </div>
        <form action="" method="post">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-dark">
                    <label>Starting currency</label>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xl-12 text-light input-icons">
                    <select class="browser-default custom-select border border-dark" name="startingCurrency">
                        <?php foreach ($this->currencyRates as $currencyRate): ?>
                            <option value="<?= $currencyRate->mid. '|' . $currencyRate->currency ?>"><?= $currencyRate->currency; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <span class="error">
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-dark">
                    <label>Target currency</label>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xl-12 text-light input-icons">
                    <select class="browser-default custom-select border border-dark" name="targetCurrency">
                        <?php foreach ($this->currencyRates as $currencyRate): ?>
                            <option value="<?= $currencyRate->mid. '|' . $currencyRate->currency ?>"><?= $currencyRate->currency; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <span class="error">
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-dark">
                    <label>Amount</label>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xl-12 text-light input-icons">
                    <input name="amount" type="text" class="form-control border border-dark" placeholder="Amount...">
                    <?php if ($this->validation->failed('amount')): ?>
                        <span class="error">
                        <?= htmlspecialchars($this->validation->message("amount")); ?>
                    </span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <button type="submit" class="btn btn-danger mb-3" name="convert">Convert</button>
            </div>
        </form>
        <div class="success">
                <div class="row">
                    <div class="col-12 text-dark">
                        <label>Result:</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 text-light">
                        <?= htmlspecialchars($this->result); ?>
                    </div>
                </div>
        </div>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="js./bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>

</body>
</html>

