<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NBP</title>
    <meta name="author" content="Mateusz Wojno">
    <meta name="description" content="NBP"/>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/style/currencyRates.css" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<nav>
<a href="currencyDenomination.php" class="btn btn-warning position-fixed top-0 m-3" style="width: 200px;"><i class="fas fa-plus"></i>Convert</a>
<a href="currencyConversionList.php" class="btn btn-warning position-fixed top-0 m-3" style="top: 50px; width: 200px"><i class="fas fa-plus"></i>Currency conversion list</a>
</nav>
<main>
    <h1 class="mb-5">Aktualne kursy walut</h1>
    <div class="container">
        <table class="table bg-danger">
            <thead class="thead-light">
            <tr>
                <th>Waluta</th>
                <th>Kod</th>
                <th>Kurs</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->currencyRates as $currencyRate): ?>
                <tr>
                    <td> <?= $currencyRate->currency; ?></td>
                    <td><?= $currencyRate->code; ?></td>
                    <td> <?= $currencyRate->mid; ?></
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</main>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="js./bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
</body>
</html>